name = "quizloop-ai"
compatibility_date = "2026-05-16"
pages_build_output_dir = "web/public"

[[d1_databases]]
binding = "DB"
database_name = "quizloop-ai"
database_id = "160afc61-9ab3-49ea-b811-f6df84c3f9db"
